import FreeCAD as App

try:
    from AxisFeature import keyway_effective_extent
except ImportError:
    def keyway_effective_extent(obj):
        # Fallback if AxisFeature isn't importable for some reason: mirror
        # the pre-Forma-C behaviour (plain position + length).
        pos = getattr(obj, "KeywayPosition", App.Units.Quantity("0mm")).Value
        return pos, getattr(obj, "KeywayLength", App.Units.Quantity("0mm")).Value

def update_axis_techdraw(axis_obj, page_obj, front_view_obj):
    """
    Cleans up old annotations and rebuilds Tiered Dimensions, 
    Groove callouts, and Keyway Section cuts on the TechDraw sheet.
    """
    doc = axis_obj.Document
    
    # 1. Clear previous auto-generated views to handle segment reordering
    for obj in list(doc.Objects):
        if getattr(obj, "AutoGeneratedByAxis", False):
            if page_obj and obj in page_obj.Views:
                page_obj.removeView(obj)
            doc.removeObject(obj.Name)

    segments = getattr(axis_obj, "Group", [])
    if not segments:
        return

    # Tier offsets from front view center (in mm)
    TIER_0_OFFSET = 12.0  # Grooves & close details
    TIER_1_OFFSET = 25.0  # Individual segment lengths
    TIER_2_OFFSET = 38.0  # Total shaft length

    base_x = front_view_obj.X
    base_y = front_view_obj.Y
    current_x = 0.0

    for idx, seg in enumerate(segments):
        seg_len = getattr(seg, "Length", App.Units.Quantity("0mm")).Value
        seg_dia = getattr(seg, "Diameter", App.Units.Quantity("0mm")).Value

        # TIER 0: GROOVE CALLOUT [Width (øRootDiameter)]
        if getattr(seg, "HasGroove", False):
            g_w = getattr(seg, "GrooveWidth", App.Units.Quantity("1mm")).Value
            g_d = getattr(seg, "GrooveDepth", App.Units.Quantity("1mm")).Value
            g_pos = getattr(seg, "GroovePosition", App.Units.Quantity("0mm")).Value
            root_dia = seg_dia - (2.0 * g_d)
            
            dim_g = doc.addObject("TechDraw::DrawViewDimension", f"Dim_Groove_{seg.Name}")
            dim_g.AutoGeneratedByAxis = True
            dim_g.Type = "DistanceX"
            dim_g.Arbitrary = True
            dim_g.FormatSpec = f"{g_w:g} (ø{root_dia:g})"
            dim_g.X = base_x + current_x + g_pos + (g_w / 2.0)
            dim_g.Y = base_y + TIER_0_OFFSET
            page_obj.addView(dim_g)

        # TIER 0: KEYWAY SECTION CUT & LEADER CALLOUT
        if getattr(seg, "HasKeyway", False):
            kw_w = getattr(seg, "KeywayWidth", App.Units.Quantity("0mm")).Value
            kw_d = getattr(seg, "KeywayDepth", App.Units.Quantity("0mm")).Value
            kw_pos, kw_l = keyway_effective_extent(seg)

            cut_x = current_x + kw_pos + (kw_l / 2.0)
            sec_symbol = chr(65 + (idx % 26))

            # Dynamic Section Cut
            sec_view = doc.addObject("TechDraw::DrawViewSection", f"Sec_Keyway_{seg.Name}")
            sec_view.AutoGeneratedByAxis = True
            sec_view.Source = [axis_obj]
            sec_view.BaseView = front_view_obj
            sec_view.SectionSymbol = sec_symbol
            sec_view.SectionNormal = App.Vector(1, 0, 0)
            sec_view.SectionOrigin = App.Vector(cut_x, 0, 0)
            sec_view.X = base_x + cut_x
            sec_view.Y = base_y - 50.0
            page_obj.addView(sec_view)

            # Leader Callout: L40xW3x2DP
            leader = doc.addObject("TechDraw::DrawLeader", f"Leader_Keyway_{seg.Name}")
            leader.AutoGeneratedByAxis = True
            leader.View = sec_view
            leader.Text = [f"L{kw_l:g}xW{kw_w:g}x{kw_d:g}DP"]
            leader.X = sec_view.X + 12.0
            leader.Y = sec_view.Y + 12.0
            page_obj.addView(leader)

        # TIER 1: SEGMENT LENGTH
        dim_s = doc.addObject("TechDraw::DrawViewDimension", f"Dim_Len_{seg.Name}")
        dim_s.AutoGeneratedByAxis = True
        dim_s.Type = "DistanceX"
        dim_s.FormatSpec = f"{seg_len:g}"
        dim_s.X = base_x + current_x + (seg_len / 2.0)
        dim_s.Y = base_y + TIER_1_OFFSET
        page_obj.addView(dim_s)

        current_x += seg_len

    # TIER 2: OVERALL LENGTH
    if current_x > 0:
        dim_total = doc.addObject("TechDraw::DrawViewDimension", f"Dim_Total_{axis_obj.Name}")
        dim_total.AutoGeneratedByAxis = True
        dim_total.Type = "DistanceX"
        dim_total.FormatSpec = f"{current_x:g}"
        dim_total.X = base_x + (current_x / 2.0)
        dim_total.Y = base_y + TIER_2_OFFSET
        page_obj.addView(dim_total)

    doc.recompute()